import os
import tomllib
from pathlib import Path

# Go to project root
os.chdir(Path(__file__).absolute().parent.parent)

with open("pyproject.toml", "rb") as f:
    content = tomllib.load(f)

with open("requirements-dev.txt", "w") as f:
    print(f"# Auto-generated by {Path(__file__).name}", file=f)
    for dep in content["project"]["dependencies"]:
        print(dep, file=f)
    for dep in content["project"]["optional-dependencies"]["dev"]:
        print(dep, file=f)

print("Wrote requirements-dev.txt")
