on:
  push:
    branches:
      - master
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements.txt -r requirements-dev.txt
    - run: |
        time mypy --platform linux --python-version 3.7 porcupine more_plugins
        time mypy --platform linux --python-version 3.8 porcupine more_plugins
        time mypy --platform linux --python-version 3.9 porcupine more_plugins
        time mypy --platform win32 --python-version 3.7 porcupine more_plugins
        time mypy --platform win32 --python-version 3.8 porcupine more_plugins
        time mypy --platform win32 --python-version 3.9 porcupine more_plugins
        time mypy --platform darwin --python-version 3.7 porcupine more_plugins
        time mypy --platform darwin --python-version 3.8 porcupine more_plugins
        time mypy --platform darwin --python-version 3.9 porcupine more_plugins
  pytest-windows:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    env:
      TCLLIBPATH: lib
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install -r requirements.txt -r requirements-dev.txt
    - run: python scripts/download-tkdnd.py
    - run: python -m pytest -vvvv --durations=10
  pytest-linux:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    # Make sure that it doesn't crash with Noto Color Emoji
    - run: sudo apt install --no-install-recommends fonts-noto-color-emoji tkdnd
    - run: pip install -r requirements.txt -r requirements-dev.txt
    - uses: GabrielBB/xvfb-action@v1.4
      with:
        run: python3 -m pytest -vvvv --durations=10
  pytest-macos:
    # https://github.com/actions/setup-python/issues/58
    # Brew-installed python 3.8 and 3.9 seem to already be there, so it's not slow
    # but starting today, 3.9 has no tkinter lol?
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    env:
      # TODO: how to install tkdnd on mac? add instructions to README or make mac app that bundles it
      TCLLIBPATH: ./lib
      PYTHON: /usr/local/opt/python@${{ matrix.python-version }}/libexec/bin/python
    steps:
    - uses: actions/checkout@v2
    - run: brew install python@${{ matrix.python-version }}
    - run: $PYTHON --version
    - run: $PYTHON -m pip install -r requirements.txt -r requirements-dev.txt
    - run: $PYTHON scripts/download-tkdnd.py
    - run: $PYTHON -m pytest -vvvv --durations=10
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements-dev.txt
    - run: python3 -m black --check scripts/*.py porcupine tests more_plugins
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements-dev.txt
    - run: python3 -m isort --check scripts/*.py porcupine tests more_plugins
  pyflakes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements-dev.txt
    - run: python3 -m pyflakes scripts/*.py porcupine tests more_plugins
  bindcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: python3 scripts/bindcheck.py porcupine
    - run: python3 scripts/bindcheck.py more_plugins
