# https://medium.com/@doedotdev/mypy-for-github-action-7da1ebee99e7
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  mypy:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - run: |
        git submodule init && git submodule update
    - run: |
        mypy porcupine more_plugins
  pytest:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - if: contains(matrix.os, 'windows')
      run: python -m pytest
    - if: ${{ !contains(matrix.os, 'windows') }}
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: |
          python3 -m pytest
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: |
        pip install -r requirements-dev.txt
    - run: |
        python3 -m pycodestyle scripts/*.py porcupine tests more_plugins
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: |
        pip install -r requirements-dev.txt
    - run: |
        python3 -m isort --check scripts/*.py porcupine tests more_plugins
  pyflakes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: |
        pip install -r requirements-dev.txt
    - run: |
        python3 -m pyflakes scripts/*.py porcupine tests more_plugins
  bindcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: |
        python3 scripts/bindcheck.py porcupine
    - run: |
        python3 scripts/bindcheck.py more_plugins
