# https://medium.com/@doedotdev/mypy-for-github-action-7da1ebee99e7
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements.txt -r requirements-dev.txt
    - run: git submodule init && git submodule update
    - run: |
        mypy --platform linux --python-version 3.6 porcupine more_plugins
        mypy --platform linux --python-version 3.7 porcupine more_plugins
        mypy --platform linux --python-version 3.8 porcupine more_plugins
        mypy --platform linux --python-version 3.9 porcupine more_plugins
        mypy --platform win32 --python-version 3.6 porcupine more_plugins
        mypy --platform win32 --python-version 3.7 porcupine more_plugins
        mypy --platform win32 --python-version 3.8 porcupine more_plugins
        mypy --platform win32 --python-version 3.9 porcupine more_plugins
  pytest-windows:
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install -r requirements.txt -r requirements-dev.txt
    - run: python -m pytest -vvvv
  pytest-linux:
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    # Make sure that it doesn't crash with Noto Color Emoji
    - run: sudo apt install fonts-noto-color-emoji
    - run: pip install -r requirements.txt -r requirements-dev.txt
    - uses: GabrielBB/xvfb-action@v1.4
      with:
        run: python3 -m pytest -vvvv
  pytest-macos:
    # https://github.com/actions/setup-python/issues/58
    # Brew-installed python 3.8 and 3.9 seem to already be there, so it's not slow
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2
    - run: brew install python@${{ matrix.python-version }}
    - run: python3 -m pip install -r requirements.txt -r requirements-dev.txt
    - run: python3 -m pytest -vvvv
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements-dev.txt
    - run: python3 -m pycodestyle scripts/*.py porcupine tests more_plugins
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements-dev.txt
    - run: python3 -m isort --check scripts/*.py porcupine tests more_plugins
  pyflakes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements-dev.txt
    - run: python3 -m pyflakes scripts/*.py porcupine tests more_plugins
  bindcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: python3 scripts/bindcheck.py porcupine
    - run: python3 scripts/bindcheck.py more_plugins
