on:
  push:
    branches:
      - docs-gh-actions

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements-dev.txt
    - run: python3 -m sphinx ./docs ./build
    - uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: build
