# See scripts/build-tree-sitter-binary.py for documentation on what this does and why.

on:
  workflow_dispatch:

jobs:
  build-binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - run: echo hello
