# One of Porcupine's two syntax highlighter plugins uses py-tree-sitter.
# py-tree-sitter wants to use a C compiler to build language definitions.
# This makes py-tree-sitter fast, but most Porcupine users don't have a C compiler.
# To work around this, we build the language definitions in GitHub Actions.
# This produces a platform-specific binary file (.dll, .dylib or .so) for each platform.
# We then collect them into a single .zip file and make a pull request that adds it to Porcupine.
# The highlighter plugin then extracts what it needs from the .zip file.
#
# To run this, use the "Run workflow" button here:
# https://github.com/Akuli/porcupine/actions/workflows/tree-sitter-binaries.yml

on:
  workflow_dispatch:
    inputs:
      make-pull-request:
        type: boolean
        description: "Create a pull request of the results"
  pull_request:   # Run the build to make sure it's successful, but don't make a pull request

jobs:
  build-binaries:
    strategy:
      matrix:
        platform:
          # These must be in sync with download-artifact below.
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python -u scripts/build-tree-sitter-binary.py
      - uses: actions/upload-artifact@v3
        with:
          name: tree-sitter-binary-${{ matrix.platform }}
          path: tree-sitter-binary-*.*

  collect-and-make-pr:
    runs-on: ubuntu-latest
    needs: [build-binaries]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: tree-sitter-binary-ubuntu-latest
      - uses: actions/download-artifact@v3
        with:
          name: tree-sitter-binary-windows-latest
      - uses: actions/download-artifact@v3
        with:
          name: tree-sitter-binary-macos-latest
      - run: zip tree-sitter-binaries.zip tree-sitter-binary-*
      - run: mv tree-sitter-binaries.zip porcupine/plugins/
      - run: rm tree-sitter-binary-*
      - if: github.event_name == 'workflow_dispatch' && github.event.inputs.make-pull-request == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          # Commit message is "[create-pull-request] automated change" by default.
          # With just one commit on PR, it shows up on master once the PR is merged.
          # I wish it defaulted to same as title...
          title: "Generate new tree-sitter binaries used for syntax highlighting"
          commit-message: "Generate new tree-sitter binaries used for syntax highlighting"
          body: >-
            This PR was generated by `.github/workflows/tree-sitter-binaries.yml`.
            This PR must be closed and then reopened to run CI checks,
            because a GitHub Actions workflow can't trigger other GitHub Actions workflows.
