# See scripts/build-tree-sitter-binary.py for documentation on what this does and why.
# To run this, use the "Run workflow" button here:
# https://github.com/Akuli/porcupine/actions/workflows/tree-sitter-binaries.yml

on:
  workflow_dispatch:

jobs:
  build-binaries:
    strategy:
      matrix:
        platform:
          # These are copied into download-artifact below.n
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python -u scripts/build-tree-sitter-binary.py
      - uses: actions/upload-artifact@v3
        with:
          name: tree-sitter-binary-${{ matrix.platform }}
          path: syntax-binary-*.*

  collect-and-make-pr:
    runs-on: ubuntu-latest
    needs: [build-binaries]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: tree-sitter-binary-ubuntu-latest
      - uses: actions/download-artifact@v3
        with:
          name: tree-sitter-binary-windows-latest
      - uses: actions/download-artifact@v3
        with:
          name: tree-sitter-binary-macos-latest
      - run: ls -l
